#!/usr/bin/env bash
# populate_thumbnail_path.sh
#
# Generates an idempotent SQL file that populates the thumbnail_path column
# in the vempain-site web_site_file table for every row where it is still NULL.
#
# All file types (images, PDFs, SVGs, videos, …) can have a .thumb JPEG
# sidecar, so no mimetype filter is applied.
#
# The thumbnail_path is derived from file_path by:
#   1. Inserting '/.thumb/' before the filename component
#   2. Replacing whatever extension the file has with '.jpg'
# Examples:
#   file_path      : image/Autot/Photos/photo.jpg
#   thumbnail_path : image/Autot/Photos/.thumb/photo.jpg
#
#   file_path      : docs/report.pdf
#   thumbnail_path : docs/.thumb/report.jpg
#
#   file_path      : vectors/logo.svg
#   thumbnail_path : vectors/.thumb/logo.jpg
#
# Required environment variables (site database):
#   VEMPAIN_SITE_DB_HOST     – hostname (default: localhost)
#   VEMPAIN_SITE_DB_PORT     – port     (default: 5433)
#   VEMPAIN_SITE_DB_NAME     – database name
#   VEMPAIN_SITE_DB_USER     – database user
#   VEMPAIN_SITE_DB_PASSWORD – database password
#   VEMPAIN_SITE_DB_SCHEMA   – schema name (default: vempain_site)
#
# Optional:
#   OUTPUT_FILE – path of the generated SQL file (default: update_thumbnail_path.sql)
#
# Usage:
#   export VEMPAIN_SITE_DB_HOST=localhost
#   export VEMPAIN_SITE_DB_PORT=5433
#   export VEMPAIN_SITE_DB_NAME=vempain_site_db
#   export VEMPAIN_SITE_DB_USER=vempain_site
#   export VEMPAIN_SITE_DB_PASSWORD=vempain_site_password
#   bash populate_thumbnail_path.sh
#   psql -h localhost -p 5433 -U vempain_site -d vempain_site_db -f update_thumbnail_path.sql

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────────
DB_HOST="${VEMPAIN_SITE_DB_HOST:-localhost}"
DB_PORT="${VEMPAIN_SITE_DB_PORT:-5433}"
DB_NAME="${VEMPAIN_SITE_DB_NAME:?VEMPAIN_SITE_DB_NAME is required}"
DB_USER="${VEMPAIN_SITE_DB_USER:?VEMPAIN_SITE_DB_USER is required}"
DB_SCHEMA="${VEMPAIN_SITE_DB_SCHEMA:-vempain_site}"
OUTPUT_FILE="${OUTPUT_FILE:-update_thumbnail_path.sql}"

export PGPASSWORD="${VEMPAIN_SITE_DB_PASSWORD:?VEMPAIN_SITE_DB_PASSWORD is required}"

PSQL_OPTS=(-h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" --no-password -t -A -F $'\t')

# ── Connectivity check ─────────────────────────────────────────────────────────
echo "[INFO] Checking connectivity to ${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME} ..."
psql "${PSQL_OPTS[@]}" -c "SELECT 1" > /dev/null
echo "[INFO] Connection OK."

# ── Fetch rows that need updating ──────────────────────────────────────────────
# We query all web_site_file rows where thumbnail_path IS NULL.
# The new thumbnail_path is derived in SQL by:
#   - capturing the directory part and the basename-without-extension
#   - inserting '/.thumb/' and forcing the extension to '.jpg'
echo "[INFO] Fetching rows with missing thumbnail_path ..."

SQL_QUERY="
SET search_path TO ${DB_SCHEMA};
SELECT
    id,
    file_path,
    regexp_replace(file_path, '^(.*)/([^/]+)\\.[^./]+$', '\\1/.thumb/\\2.jpg') AS computed_thumbnail_path
FROM web_site_file
WHERE thumbnail_path IS NULL
ORDER BY id;
"

ROWS=$(psql "${PSQL_OPTS[@]}" -c "$SQL_QUERY")

ROW_COUNT=$(echo "$ROWS" | grep -c . || true)
if [[ -z "$ROWS" ]]; then
    ROW_COUNT=0
fi
echo "[INFO] Found ${ROW_COUNT} row(s) that need a thumbnail_path value."

# ── Generate SQL file ──────────────────────────────────────────────────────────
{
    echo "-- Generated by populate_thumbnail_path.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "-- Idempotent: each UPDATE uses WHERE thumbnail_path IS NULL so re-running is safe."
    echo "-- Apply to: ${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME} (schema: ${DB_SCHEMA})"
    echo ""
    echo "SET search_path TO ${DB_SCHEMA};"
    echo ""

    if [[ -z "$ROWS" ]]; then
        echo "-- No rows found with missing thumbnail_path; nothing to do."
    else
        echo "BEGIN;"
        echo ""

        while IFS=$'\t' read -r id file_path computed_thumbnail_path; do
            # Guard: skip rows where the regex did not transform the path
            # (e.g. files without an extension or without a directory component)
            if [[ "$file_path" == "$computed_thumbnail_path" ]]; then
                echo "-- SKIPPED id=${id}: could not derive thumbnail_path from file_path='${file_path}'"
                continue
            fi

            # Escape single quotes in path values (PostgreSQL literal escaping)
            safe_thumb=$(echo "$computed_thumbnail_path" | sed "s/'/''/g")

            echo "UPDATE web_site_file"
            echo "    SET thumbnail_path = '${safe_thumb}'"
            echo "    WHERE id = ${id}"
            echo "      AND thumbnail_path IS NULL;"
            echo ""
        done <<< "$ROWS"

        echo "COMMIT;"
    fi

    echo ""
    echo "-- Done."
} > "$OUTPUT_FILE"

echo "[INFO] SQL file written to: ${OUTPUT_FILE}"
echo "[INFO] Review the file, then apply it with:"
echo "       psql -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER} -d ${DB_NAME} -f ${OUTPUT_FILE}"
