#!/usr/bin/env bash

# Check that this script is being run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root"
  exit 1
fi

TEST_PROPERTY_FILE="service/src/test/resources/application.properties"

echo "This script will clean up the setup generated by the testSetup.sh script. It will remove both users and directories created by the script."
echo "It uses the values from the ${TEST_PROPERTY_FILE} file to set up the environment. This"
echo "includes users and directories. Please review the property file before running this script to fully understand the changes."
echo
echo "Do you want to continue? (y/n)"
read answer

if [ "$answer" == "${answer#[Yy]}" ] ;then
    echo "Test environment setup cancelled! Exiting..."
    exit 0
fi

# Read the property file
echo "Reading the property file ${TEST_PROPERTY_FILE}"
# Read the properties file and assign variables
while IFS='=' read -r key value; do
  # Skip empty lines and comments
  if [ -z "$key" ] || [[ "$key" == \#* ]]; then
    continue
  fi
  key=$(echo $key | tr '.' '_' | tr '-' '_')  # Replace '.' or '-' with '_' in the key (optional)
  eval "${key}=\"${value}\""
  echo "Set ${key}='${value}'"
done < "${TEST_PROPERTY_FILE}"

# Make sure the user wants to run the script
echo "These are the settings the script will use. Do you want to continue? (y/n)"
read answer

if [ "$answer" == "${answer#[Yy]}" ] ;then
    echo "Test environment setup cancelled! Exiting..."
    exit 0
fi

echo "Removing directory: ${vempain_admin_file_converted_directory}"
rm -rf "${vempain_admin_file_converted_directory}"

echo "Deleting user account: ${vempain_admin_ssh_user}"
userdel -rf "${vempain_admin_ssh_user}"

echo "Deleting user account: ${vempain_site_ssh_user}"
userdel -rf "${vempain_site_ssh_user}"

echo "Removing directory: ${vempain_site_www_root}"
rm -rf "${vempain_site_www_root}"

echo "Removing directory: ${vempain_site_ssh_home_dir}"
rm -rf "${vempain_site_ssh_home_dir}"
