spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: info
    fi:
      poltsi: debug
      poltsi.vempain.auth: info
vempain:
  cmd-line:
    exiftool: "/usr/bin/exiftool"
