spring:
  config:
    activate:
      on-profile: prod
  # These need to be in place so that application can find the drivers
  admin-datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  site-datasource:
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
      hibernate:
        SQL: WARN
