/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fi.poltsi.vempain;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
public class VempainAdminApplication {
	public static void main(String[] args) {
		SpringApplication.run(VempainAdminApplication.class, args);
	}
}
