package fi.poltsi.vempain.admin.api.request;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;
import tools.jackson.databind.PropertyNamingStrategies;
import tools.jackson.databind.annotation.JsonNaming;

import java.time.Instant;

/**
 * Creation of a service-to-service API token. The token string itself is generated by the server and returned exactly once.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Schema(name = "ApiTokenRequest", description = "New service-to-service API token")
public class ApiTokenRequest {
	@Schema(description = "What the token is used for", example = "vempain-file-backend production", requiredMode = Schema.RequiredMode.REQUIRED)
	@NotBlank
	@Size(max = 255)
	private String description;

	@Schema(description = "IPv4 or IPv6 network the token may be used from, in CIDR notation; a plain address means a single host (/32 or /128)",
			example = "10.0.0.0/24", requiredMode = Schema.RequiredMode.REQUIRED)
	@NotBlank
	@Size(max = 64)
	private String network;

	@Schema(description = "When the token stops working; must be in the future", example = "2027-01-01T00:00:00Z", requiredMode = Schema.RequiredMode.REQUIRED)
	@NotNull
	@Future
	@DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME)
	private Instant expiresAt;
}
